default_language_version:
  python: python3.11

minimum_pre_commit_version: 3.3.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            .*\.json-result|
            .*\.min.js|
            .*\.min.css.*
          )$
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore|
            \.vscode/dictionaries/.*\.txt|
            MANIFEST.in
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            (.*)?(cdk|tsconfig|tslint).json
          )$
      - id: trailing-whitespace
        exclude_types: ["markdown"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.12
    hooks:
        - id: pymarkdown
          args:
              - --config=.pymarkdown-linting-cfg.json
              - scan
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
