# Dev Environment
SHELL=/bin/bash

# Visual Studio devcontainers
build:
	mkdocs build

lint:
	@pymarkdownlnt -c .pymarkdown-linting-cfg.json scan --recurse docs

serve:
	mkdocs serve

check:
	pre-commit run --all-files
